# Generated by Django 5.0.6 on 2026-05-21 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('download', 'Download'), ('upload_version', 'Upload Version'), ('approve', 'Approve'), ('reject', 'Reject'), ('share', 'Share'), ('share_access', 'Shared Link Access'), ('sign', 'Digital Signature Applied'), ('legal_hold', 'Legal Hold Applied'), ('legal_hold_lift', 'Legal Hold Lifted'), ('destroy', 'Destroyed'), ('custody_transfer', 'Custody Transfer'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('export', 'Export')], max_length=30)),
                ('record_reference', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CustodyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('both', 'Both')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-transferred_at'],
            },
        ),
    ]
