# Generated by Django 5.0.6 on 2026-05-21 09:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('retention_years', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='records.recordseries')),
            ],
            options={
                'verbose_name': 'Record Series',
                'verbose_name_plural': 'Record Series',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('correspondence', 'Correspondence'), ('personnel_file', 'Personnel File'), ('board_paper', 'Board Paper'), ('policy', 'Policy Document'), ('circular', 'Circular'), ('report', 'Report'), ('submission', 'Commission Submission'), ('disciplinary', 'Disciplinary File'), ('contract', 'Contract'), ('financial', 'Financial Document'), ('legal', 'Legal Document'), ('other', 'Other')], default='other', max_length=30)),
                ('classification_level', models.CharField(choices=[('unclassified', 'Unclassified'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('secret', 'Secret')], default='internal', max_length=20)),
                ('originating_ministry', models.CharField(blank=True, max_length=200)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('physical_file_ref', models.CharField(blank=True, max_length=200)),
                ('physical_location', models.CharField(blank=True, max_length=300)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_vital', models.BooleanField(default=False)),
                ('is_on_legal_hold', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('retention_date', models.DateField(blank=True, null=True)),
                ('scheduled_destruction_date', models.DateField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_records', to=settings.AUTH_USER_MODEL)),
                ('custodian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_records', to=settings.AUTH_USER_MODEL)),
                ('destruction_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destroyed_records', to='compliance.destructioncertificate')),
                ('related_records', models.ManyToManyField(blank=True, to='records.record')),
                ('record_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='records.recordseries')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='records/versions/')),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('content_hash', models.CharField(max_length=64)),
                ('ocr_text', models.TextField(blank=True)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('ocr_language', models.CharField(blank=True, max_length=20)),
                ('ai_suggestions', models.JSONField(blank=True, default=dict)),
                ('ai_processed', models.BooleanField(default=False)),
                ('is_signed', models.BooleanField(default=False)),
                ('signature_info', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_versions', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='records.record')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_download', models.BooleanField(default=True)),
                ('can_share', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to='accounts.department')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='records.record')),
            ],
            options={
                'unique_together': {('record', 'department'), ('record', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='record',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='record_search_gin'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['reference_number'], name='records_rec_referen_6bb762_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['document_type'], name='records_rec_documen_3117b8_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['classification_level'], name='records_rec_classif_d3411a_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['created_at'], name='records_rec_created_85482c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recordversion',
            unique_together={('record', 'version_number')},
        ),
    ]
