# Generated by Django 5.0.6 on 2026-05-21 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalhold',
            name='record_series',
            field=models.ManyToManyField(blank=True, related_name='legal_holds', to='records.recordseries'),
        ),
        migrations.AddField(
            model_name='legalhold',
            name='records',
            field=models.ManyToManyField(related_name='legal_holds', to='records.record'),
        ),
        migrations.AddField(
            model_name='retentionschedule',
            name='record_series',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_schedule', to='records.recordseries'),
        ),
    ]
